version: 1.0.0
workspace: null
config_path:
language: zh
model:
  type: openai
  api_key: NoKeyNeededNow
  endpoint: http://10.1.110.2:8888/deepseek-v3/v1
  model: Deepseek-V3
user_model:
  type: openai
  api_key: NoKeyNeededNow
  endpoint: http://10.1.110.2:8888/deepseek-v3/v1
  model: Deepseek-V3
server:
  host: 127.0.0.1
  port: 8000
  frontend_port: 5173
